export const SET_HEADER_RIGHT = 'SET_HEADER_RIGTHT';
export const SET_HEADER_SEARCH = 'SET_HEADER_SEARCH';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SELECT_PARADA = 'SELECT_PARADA';
export const UPTADE_PARADAS = 'UPTADE_PARADAS'